version: '3'
services:
  web:
    build:
      context: .
      dockerfile: devops/web/Dockerfile
    container_name: web
    tty: true
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    depends_on:
      - app
      - db
      - redis
    networks:
      backend:
        ipv4_address: 172.77.1.2

  app:
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 40s php-fpm
    build:
      args:
        - USER_UID=1000
        - USER_GID=1000
      context: .
      dockerfile: devops/app/Dockerfile
    volumes:
      - .:/var/www
    depends_on:
      - db
      - redis
    networks:
      backend:
        ipv4_address: 172.77.1.3

  db:
    container_name: db
    command: --innodb-use-native-aio=0
    build:
      args:
        - USER_UID=1000
        - USER_GID=1000
      context: .
      dockerfile: devops/db/Dockerfile
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=users
      - MYSQL_ROOT_PASSWORD=root
    networks:
      backend:
        ipv4_address: 172.77.1.4

  redis:
      image: redis:alpine
      container_name: redis
      expose:
          - 6379
      networks:
        backend:
          ipv4_address: 172.77.1.5

networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.77.1.0/24
